# Generated by Django 3.2.5 on 2021-07-07 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estrategia', models.TextField(verbose_name='Estrategia')),
                ('problema', models.TextField(verbose_name='Problema')),
            ],
            options={
                'verbose_name': 'Eje',
                'verbose_name_plural': 'Ejes',
            },
        ),
        migrations.CreateModel(
            name='FactorDesagregacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'FactorDesagregacion',
                'verbose_name_plural': 'Factores de Desagregacion',
            },
        ),
        migrations.CreateModel(
            name='FuenteInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Fuente de Informacion',
                'verbose_name_plural': 'Fuentes de Informacion',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fuente_verificacion', models.TextField(verbose_name='Fuente de Verificacion')),
                ('formula', models.TextField(verbose_name='Formula')),
                ('plazo', models.IntegerField(choices=[(1, 'Corto'), (2, 'Medio'), (3, 'Largo')], default=1, verbose_name='Plazo')),
                ('fuentes_informacion', models.ManyToManyField(related_name='indicadores', to='violencia.FuenteInformacion')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento', to='violencia.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='ValorFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200, verbose_name='Valor')),
                ('codigo', models.CharField(max_length=4, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Valor de Factor',
                'verbose_name_plural': 'Valor de Factores',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violencia.variable')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(verbose_name='Resultado')),
                ('presupuesto', models.TextField(verbose_name='Presupuesto')),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violencia.eje', verbose_name='')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('factores', models.ManyToManyField(related_name='reportes', to='violencia.FactorDesagregacion')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='violencia.indicador')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='violencia.municipio')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.AddField(
            model_name='indicador',
            name='instituciones',
            field=models.ManyToManyField(related_name='indicadores', to='violencia.Institucion'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violencia.resultado'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='variables',
            field=models.ManyToManyField(related_name='indicadores', to='violencia.Variable'),
        ),
    ]
