# Generated by Django 3.2.5 on 2021-07-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('violencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorfactor',
            name='factor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='factor', to='violencia.factordesagregacion'),
            preserve_default=False,
        ),
    ]
