# Generated by Django 3.2.5 on 2021-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violencia', '0002_valorfactor_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factordesagregacion',
            name='codigo',
            field=models.CharField(default=None, max_length=50, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
